### ISSUE TITLE
List of machines should have the machine category

### ISSUE THREAD

**Issue by vmatare** [carologistics/rcll-refbox-frontend#26]
To make the frontend more easily understandable for newcomers and spectators, each machine should have its machine type on top of it, so that it looks similar to this:
```
[ Cap Station ]
C-CS1    IDLE
C_Z23
```

**Comment by morxa** [comment]
We discussed this today and decided that we do not want to have this feature: The frontend is not intended to be used by spectators and newcomers who don't know what CS stands will likely not be able to use the frontend in a meaningful way.
