### ISSUE TITLE
Interactable UI elements should be visually recognizable

### ISSUE THREAD

**Issue by vmatare** [carologistics/rcll-refbox-frontend#4]
Saw a quick demo of the new RefBox interface on the Carologistics meeting today, looks very promising!

A few usability issues were noted. One of them is the fact that active GUI elements should be recognizable as such. So in every GUI you have to have some conventionalized distinction between clickable/interactable stuff and non-interactable elements. Traditionally, it's this 3D shading effect you often see on buttons, a shaded inset frame on editable boxes, etc.

Doesn't even matter that much how you make the distinction, it could also be color, a hover effect (less preferred because it's not immediately visible) or a different drawing style. But some kind of distinction has to be there, because without it the UI becomes quite unapproachable.

It's important to recognize that this UI will be used by people possibly under significant cognitive, sensory and emotional stress.

**Comment by userin4o** [comment]
Thanks for the polite feedback. I made all UI elements interactive as suggested.
