### ISSUE TITLE
Dark background should be dark

### ISSUE THREAD

**Issue by vmatare** [carologistics/rcll-refbox-frontend#5]
The background color we saw in the demo today was too bright for a dark background. So generally, if you have a dark background with bright text, the background should actually be very dark, i.e. much closer to `#000`. Otherwise you end up with too many colors you can't use for informative elements because the contrast is too low. Also remember that the UI may have to be used in difficult viewing conditions, e.g. on a bad screen with sunlight shining on it, further worsening the contrast ratio.

**Comment by userin4o** [comment]
Thanks! I darkened out the background and the colors are much more contrasting.
